apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-core-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-core-service
  template:
    metadata:
      labels:
        app: delivery-core-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: delivery-core-service
          image: sekretaria/corelab12:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: delivery-config
            - secretRef:
                name: db-credentials
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "1"
              memory: "1024Mi"